---
# Set some vars based on distribution type
- include_tasks: facts.yml

# Set up the server side first
- include_tasks: server.yml
  when: rsnapshot_backup_root is defined

# Set up the client side
- include_tasks: client.yml
  when: backup_dirs is defined

# Set up an SSH proxy for backing up proxied hosts
- include_tasks: proxy.yml
  when: backup_proxy is defined
