---
# Set some vars based on distribution type
- name: Include facts
  ansible.builtin.include_tasks:
    file: facts.yml

# Set up the server side first
- name: Include server tasks
  ansible.builtin.include_tasks:
    file: server.yml
  when: rsnapshot_backup_root is defined

# Set up the client side
- name: Include client tasks
  ansible.builtin.include_tasks:
    file: client.yml
  when: backup_dirs is defined

# Set up an SSH proxy for backing up proxied hosts
- name: Include proxy tasks
  ansible.builtin.include_tasks:
    file: proxy.yml
  when: backup_proxy is defined
